<?
$PERM["video"]["*"]="R";
$PERM["html"]["10"]="R";
$PERM["html"]["*"]="D";
$PERM["potokin"]["10"]="D";
$PERM["/"]["5"]="R";
$PERM["/"]["11"]="R";
$PERM["/"]["26"]="W";
$PERM["/"]["*"]="R";
$PERM["bitrix"]["5"]="R";
$PERM["bitrix"]["26"]="R";
$PERM["1c_exchange"]["18"]="R";
$PERM["1c_exchange"]["*"]="D";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["upload"]["25"]="T_8";
$PERM["myscr"]["6"]="X";
$PERM["personal"]["7"]="W";
$PERM["news"]["7"]="W";
$PERM["about"]["7"]="W";
$PERM["index.php"]["7"]="W";
?>